includes:
  - path: deployment

commonLabels:
  my.prefix/environment: "{{ args.environment }}"
  my.prefix/deployment-project: k8s-deployment-simple

deleteByLabels:
  my.prefix/environment: "{{ args.environment }}"
  my.prefix/deployment-project: k8s-deployment-simple

args:
  - name: environment
